name: 機能提案
description: 改善案や新機能を提案する
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: 解決したい課題
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 提案する解決策
    validations:
      required: true
